### ISSUE TITLE
Slow response for recommended songs(only first time login)

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Team-Rocket#112]
Recommendation Engine takes a lot of time to generate recommended songs when user logs in for the first time.

**Comment by aravindparappil46** [comment]
Taking 2-3 mins for set of songs to load when you log in for the first time and say, click on a mood card

**Comment by aravindparappil46** [comment]
Don't think this is an issue with Reco Engine as clicking on mood card doesn't hit the RecoEngine service.
Response is slow for the first time even when a normal search is performed. However, once the first set of songs gets loaded (either through a search or through a mood card), every other request happens really fast.
@sairohithA007 @ATarfe any thoughts on why this might be happening?

**Comment by ATarfe** [comment]
Is it because we have two services on a single instance?

**Comment by sairohithA007** [comment]
I think that the initial contact with Spotify to get the token might be time consuming and delaying the communication between micro-services. Need to test this scenario and observe the processing time.

**Comment by aravindparappil46** [comment]
@ATarfe , Only the RecoEngine and API Gateway are bundled together in a small instance (not tiny). Every other instance runs on its own separate VM

@sairohithA007 This might be the case. But the same was not happening during Milestone 1, which begs the question whether this is an issue with our many layers of middle-men (API Gateway and Zookeeper) and/or the infra in which the services are running

**Comment by ATarfe** [comment]
Exactly, as every other service is running perfectly except the RecoEngine.

**Comment by aravindparappil46** [comment]
As mentioned in my second comment, I don't think its a RecoEngine issue. Even normal search/mood tiles take 2-3 mins to give response

**Comment by prathameshd** [comment]
This issue has been fixed.
