### ISSUE TITLE
Peer Review Milestone2

### ISSUE THREAD

**Issue by BBaggines** [airavata-courses/Team-Rocket#117]
Hi Team-Rocket,
The Wiki was a great read and gave me a clean overview of what the team is trying to achieve.
Can you share the username and password for Jenkins which can help me check the deployment of various services? You can mail it to me at sbaranwa@iu.

**Comment by sairohithA007** [comment]
Hi @BBaggines ,
We have dropped an email to you with Jenkins credentials.
Thanks.

**Comment by tylerthedeveloper** [comment]
Can you mail me them too @sairohithA007

**Comment by sairohithA007** [comment]
sure @tylerthedeveloper.

**Comment by BBaggines** [comment]
Hey @sairohithA007,
I logged in through the account I had created in the morning. On hitting submit, it gives a pop up saying logged in. However, the page did not redirect anywhere. I am not sure if this is expected or I am missing something.
Below is the screenshot of the screen: 
![image](https://user-images.githubusercontent.com/6296880/53704716-30654f00-3ded-11e9-8662-1a4803fd3c3d.png)
As you an see, i am logged in but i am not sure of how to proceed to the dashboard to search for music. Clicking on Utopia symbol does not redirect too.

Regards,
Shradha Baranwal

**Comment by BBaggines** [comment]
I was able to log in again after logging out and reach the dashboard. However, clicking on Utopia from dashboard leads me back to the above page where I am kind of stuck and unable to go the dashboard.
Also, there is an option of signing up even if you are logged in which I feel is unnecessary.

Apart from that, the look and feel of the app is great. I would definitely use it. It is intuitive. The dummy commit triggered the build as expected. I am convinced of the architecture that has been implemented for the project. I am not clear on the need of APIBroker which i will hopefully understand during the presentation.

Great work!!

Regards,
Shradha Baranwal

**Comment by aravindparappil46** [comment]
Thanks for your feedback, @BBaggines ! I have raised an issue for the same #123 

The sign up button even when logged in shouldn't be showing up. Hopefully, it'll get fixed when the incorrect redirection error is fixed.

APIBroker is the intermediary for all Spotify related tasks.  The UI doesn't make any spotify calls directly, rather it is directed to the APIGateway and from there to the APIBroker, whose sole task is to make requests to Spotify API
