### ISSUE TITLE
General Suggestions + Peer review

### ISSUE THREAD

**Issue by tylerthedeveloper** [airavata-courses/Team-Rocket#118]
0. There are a ton of branches... I doubt this is intentional but I would strongly suggest both deleting and naming them appropriately 

1. After signup is it possible to automatically log me in?
1.1 if not above, can you at least take me to log in page?

2. Once logged in the search box doesn't have a search button... please add
2.1 Autocomplete would be an awesome enhancement

3. are there other moods that could be added?
3.1 could i add my own mood?

4. The player is at the bottom... would be much better at top and not get filtered away / maybe on the fixed on one of the side bars

5. the home page is sign up even if i am logged in, let's have some conditional to avoid that 

6. maybe a close button on "profile" page

**Comment by aravindparappil46** [comment]
Thanks for your suggestions, Tyler! Will definitely consider these to our backlog.

As for specifics
3. This feature is currently not there.
4. We are planning to make the player sticky, so that even if the result cause a scroll, it'll still be accessible

**Comment by tylerthedeveloper** [comment]
Thanks for the followup, I am content; everything seemed good with CI/CD as well !
