### ISSUE TITLE
Peer Review for Project 2

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Team-Rocket#120]
Great explanation and documentation. I really liked that you have separately mentioned the improvements made over Project 1, it saves a lot of rework. For now I will need following things:

1. Jenkins userid and password (You can email it to me at mbelnek@iu.edu)
2. Is there a way I can check you zookeeper instance (I am not sure if thats possible, in consul we have a web UI as well.)

P.S. I apologize for joining the party so late. Hope we can finish this on time!

**Comment by aravindparappil46** [comment]
Hi Mahesh,
Have sent you the credentials. Since we have an active bug #113 , I recommend that you run Job_ZK_Clean (which is the entry point for the jobs) first, to clear out zookeeper

Unfortunately, I do not think we have enabled zookeeper monitor @sairohithA007  thoughts?

**Comment by sairohithA007** [comment]
Actually we never had a thought to install/enable a UI for monitoring zookeeper. We will learn about it and try implementing it in next milestone.
Thanks for the idea @maheshbelnekar .

**Comment by maheshbelnekar** [comment]
The project looks solid and even the jenkins build works great! Except for the known issues I did not come across  and other issue. I can see you have already open the logout issue which I faced.
I was really looking forward to seeing zookeeper in actions but the documentation describes it well and is good enough for understanding. And a big plus for being active on github.
Good work guys!

**Comment by aravindparappil46** [comment]
@maheshbelnekar Thank you so much for your review!
