### ISSUE TITLE
Wiki for milestone 3

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Team-Rocket#144]
Hi Team,
Can you guys update the wiki for milestone 3?

Thanks,
Alakh

**Comment by aravindparappil46** [comment]
Hi Alakh,
We are updating a few details. It will be up in half an hour

**Comment by prathameshd** [comment]
Hi Alakh,
The wiki has been updated. Can you check?
Thanks

**Comment by alakhsingh** [comment]
Can you please mail Jenkins credentials to araghuv@iu.edu

Thanks,
Alakh

**Comment by alakhsingh** [comment]
Hi Team,
Great work.
UI looks neat.
The suggestions work well. 
Jenkins CI/CD works well.

Suggestions:
It would be great if you guys can have a single login rather than 2 which I feel is not needed. 

Thanks,
Alakh
