### ISSUE TITLE
[Login] Issue

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Team-Rocket#148]
Hi Team,

I logged in using the given credentials.
I am trying to understand why I had to log in through spotify again.
![image](https://user-images.githubusercontent.com/20154848/55511692-3b4f1180-562f-11e9-9cb5-6f2f8c515a60.png)

But if that was the original logging in part then why is 'aravind' displayed on the navbar ?
![image](https://user-images.githubusercontent.com/20154848/55511740-4efa7800-562f-11e9-8421-669bad3cf3f4.png)

Thanks,
Alakh

**Comment by prathameshd** [comment]
Alakh,
We have mentioned in the Wiki that having a Spotify Account is a prerequisite to use Utopia.

**Comment by alakhsingh** [comment]
Hi Prathamesh,
Okay, I understand but why is my name not displayed on the navbar when I have logged in using spotify?

Thanks,
Alakh

**Comment by prathameshd** [comment]
Alakh,
The Spotify login is required for getting access to Spotify API. You will not be logged in to Utopia with your Spotify account. You can use the application with your Utopia credentials.

**Comment by alakhsingh** [comment]
Hi,
Oh. Alright. Closing the issue.
