### ISSUE TITLE
MS3: User Module- User Registration fails

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Team-Rocket#151]
User registration fails with following error.

(Copied from browser console).

xhr.js:173 POST http://149.165.171.8:30003/auth/register 500 (Internal Server Error)
dispatchXhrRequest @ xhr.js:173
xhrAdapter @ xhr.js:18
dispatchRequest @ dispatchRequest.js:49
Promise.then (async)
request @ Axios.js:55
wrap @ bind.js:11
onSubmit @ Register.js:34
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:571
executeDispatchesInOrder @ react-dom.development.js:596
executeDispatchesAndRelease @ react-dom.development.js:695
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:704
forEachAccumulated @ react-dom.development.js:676
runEventsInBatch @ react-dom.development.js:844
runExtractedEventsInBatch @ react-dom.development.js:852
handleTopLevel @ react-dom.development.js:5027
batchedUpdates$1 @ react-dom.development.js:20269
batchedUpdates @ react-dom.development.js:2246
dispatchEvent @ react-dom.development.js:5107
interactiveUpdates$1 @ react-dom.development.js:20331
interactiveUpdates @ react-dom.development.js:2267
dispatchInteractiveEvent @ react-dom.development.js:5083
Register.js:52 Error registering...! Error: Request failed with status code 500
    at createError (createError.js:17)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:78)

**Comment by prathameshd** [comment]
Yes we are aware of this issue, we are working on it

**Comment by sairohithA007** [comment]
@harishmaruthi This issue is fixed, please refer #186

**Comment by harishmaruthi** [comment]
Thank you @sairohithA007, for the update.
Very well done.
Could you also please state the cause and fix provided on this thread. Helps in future for reference.

For now I will be closing this issue.

Thanks,

Harish.

**Comment by sairohithA007** [comment]
@harishmaruthi 
The google's SMTP is not working on Kubernetes and it is throwing an error during email delivery. Now we have moved to AWS SES for sending emails from google's smtp email system and have fixed the sign up related issue.

I have deployed it on both IU and TACC jet streams, but this is not committed to Project-4 and Project-4-Blue branches. Probably, we might merge it tomorrow. As we are using AWS SES sandbox account, we have to white list email ids to which emails have to be sent. If you want to test signup feature please send those email id's to me and I will white list those email ids on AWS SES account.

Check #186 for commits

**Comment by harishmaruthi** [comment]
Thank you that was very informative and useful.
