### ISSUE TITLE
Develop Blue Green Deployment Strategy

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/Team-Rocket#180]
Setup git branches to reflect BG deployment.
Blue - new version
Green - old version

>> Involves Jenkins job creation
>> Configuring params in config.json

**Comment by sairohithA007** [comment]
Finish setting up the git branches and implemented the blue green strategy

**Comment by aravindparappil46** [comment]
Changed jenkins jobs and set up slave configuration for TACC
