### ISSUE TITLE
Create Documentation for Milestone 4

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/Team-Rocket#181]
Wiki should be updated

**Comment by sairohithA007** [comment]
Documented blue green implemented strategy and testing strategy.

**Comment by aravindparappil46** [comment]
Updated the wiki for testing instructions and description of tasks done.
See [revision history](https://github.com/airavata-courses/Team-Rocket/wiki/Project-Milestone-4/_history) for details
