### ISSUE TITLE
Golang installation procedure should be more clear and documented.

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/Team-Rocket#52]
Pre-requisites and setting recommendation engine path should be more clearly documented.

**Comment by prathameshd** [comment]
GOPATH setting instructions for Mac/Linux has been given as per our project's needs. You just have to copy and paste the export cmd.
However, in windows, you would have to go to your 'Set system environment variables' option and add the same path in the PATH variable (link has been provided in the README.md)

Will add more details in the README.md
