### ISSUE TITLE
Bad folder structure

### ISSUE THREAD

**Issue by AdithyaHS** [airavata-courses/Team-Rocket#54]
Nested Recommendation engine folders.

**Comment by prathameshd** [comment]
Go's folder hierarchy is different from other languages. It should look like the following:

<GoWorkspace> --> src --> <GoProject>

All Go projects should go inside the src (however, we have only 1 Go Project) else GOPATH config gets messed up.

We understand the confusion here as both our GoWorkspace and the GoProject is named as RecommendationEngine. Will change that to more intuitive names.

**Comment by aravindparappil46** [comment]
@AdithyaHS Changed the workspace folder name so that it doesn't cause confusion with the inner RecommendationEngine folder. Updated README.md as well.

Closing this issue
