### ISSUE TITLE
Skip-login bug 

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/Team-Rocket#55]
Hi @airavata-courses/team-rocket ,

I was able to skip login for your application. Could you please take a look.

**Comment by ATarfe** [comment]
Is this the case with two different tabs or were you able to skip the login completely?

**Comment by morparia-p** [comment]
I logged in once and was able to use the dashboard URL to access the app again in a new session without logging in.

**Comment by sairohithA007** [comment]
1. Once you login to the application and open the dashboard in new tab, you will be able to access the music player and other features of the application.
2. Currently, we did not implement logout feature, once we implement that feature will consider this scenario.

**Comment by sairohithA007** [comment]
Fixed this issue. You can check the commit [here](https://github.com/airavata-courses/Team-Rocket/commit/bd24e53a88440e29f32095490ee83e9a3f663425)

**Comment by morparia-p** [comment]
Hey! The Authentication worked well.
I will close this issue for now.
