### ISSUE TITLE
UI/UX : Login / Sign Up redundant on login header

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Team-Rocket#60]
UI Looks good!
Observation / Suggestion:
If the user is prompted to login/Signup on the screen, that header shouldn't suggest the same
![issue1](https://user-images.githubusercontent.com/7594406/52515842-fdb1a780-2bee-11e9-952b-cc292e035af7.JPG)

**Comment by ATarfe** [comment]
Hi @rojaraman ,

I followed design standards for landing pages, used in websites such as 'https://github.com/', etc. Although, I updated the same by taking off the Login button. Please do review the issue.

Thank you.
