### ISSUE TITLE
User logged out on click of signup /Login

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Team-Rocket#61]

**Comment by sairohithA007** [comment]
Hi Roja,
I'm trying re-produce the issue, but not able to do it.
Can you please provide steps to re-produce it?

Thanks,
Sai Rohith Achanta.

**Comment by rojaraman** [comment]
Login to the website and then click on Signup or login. The user gets to signup and log-in again.

**Comment by sairohithA007** [comment]
Thanks for providing the steps to re-produce. After going through your steps, it seems that you are using the older version of the application. The newer version does not have login and signup once the user login's to the application.
Can you please pull the latest from "Project-1" branch and check if the issue still persists?
