### ISSUE TITLE
Test in AuthService failed

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Team-Rocket#62]
Not sure if this was implemented completely, tried to execute it according to Readme.md provided.
Received following

> py -3 -m unittest tests.login_test
.EF
======================================================================
ERROR: test_login_with_proper_credentials (tests.login_test.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Documents\Spring2019\SGA\TeamRocket\Team-Rocket\AuthServices\tests\login_test.py", line 15, in test_login_with_proper_credentials
    assert response.token is not None
AttributeError: 'str' object has no attribute 'token'

======================================================================
FAIL: test_login_with_wrong_password (tests.login_test.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Documents\Spring2019\SGA\TeamRocket\Team-Rocket\AuthServices\tests\login_test.py", line 29, in test_login_with_wrong_password
    assert response == "Invalid Credentials"
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 2.778s

FAILED (failures=1, errors=1)
> py -3 -m unittest tests.registration_test
...
----------------------------------------------------------------------
Ran 3 tests in 0.881s

OK

**Comment by sairohithA007** [comment]
Hi Roja,
Fixed the issue. 
Can you please check?

Thanks,
Sai Rohith Achanta.

**Comment by rojaraman** [comment]
Looks good. closing the issue
