### ISSUE TITLE
Spotify permission/authentication requested every time after login

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Team-Rocket#63]
![issue2](https://user-images.githubusercontent.com/7594406/52515922-28e8c680-2bf0-11e9-8a42-a629a8fd5b30.JPG)

I suggest prompting for permission only 1 time after the profile is created.

**Comment by aravindparappil46** [comment]
Hi @rojaraman 
Unfortunately, since we need Spotify's auth token in addition to our own JWT, it is required that we ask for Spotify login. The auth token expires in 1 hr and we do not think it's a good idea to store the token in DB and check if it's valid or not with each login.

**Comment by rojaraman** [comment]
ok. Makes sense. closing the issue.
