### ISSUE TITLE
DOM error and status 400 in console after every reload.

### ISSUE THREAD

**Issue by rojaraman** [airavata-courses/Team-Rocket#64]
Attached screenshot for your reference.
![issue4](https://user-images.githubusercontent.com/7594406/52515956-c6dc9100-2bf0-11e9-9570-fbcd6f7ff729.JPG)

**Comment by aravindparappil46** [comment]
Hi Roja,
This has been fixed. Please see commit linked. It can also be pulled from Project-1 branch.
