### ISSUE TITLE
Validation For login and password

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/Team-Rocket#71]
Hey @airavata-courses/team-rocket , 

The authentication patch was nicely fixed. Found the that form was unable to validate username and password while log in and registration.

**Comment by aravindparappil46** [comment]
Thanks for raising this! We have done the validation at the backend, however, the front end does not show appropriate messages to the use. Will take it up during Project 2 Milestone

**Comment by prathameshd** [comment]
@morparia-p We have added the appropriate messages for authentication. Closing this issue.
