### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Team-Rocket#77]
Hi Team,
I am reviewing your assignment 1 submission.

Is it necessary to have a spotify account to use the application?

**Comment by ATarfe** [comment]
Yes, it is one of the prerequisites for the application.

**Comment by raghu2094** [comment]
Ok so my second question is if the user has to login to spotify why would he/she use your application. Correct me if I am wrong, but doesn't spotfiy do all the things which your application is intending to do. Search songs, recommend songs based on the mood etc.

PS: Please don't close the issue. I will be posting my feedback here.

**Comment by raghu2094** [comment]
I am trying to understand the working here. 
1) What does the Spotify API fetch? 
2) Are you desinging your own recommendation algorithm or using the recommendations of Spotify. 
3) Similarly are you using the Spotify's user history or using your own mechanism of storing user data.

**Comment by ATarfe** [comment]
Answers regarding the working of Utopia:

1. The Spotify API fetches the song details (song name, album name, artists, Valence, etc.)
2. The Spotify API also gives the recommendations for the user.
3. Lastly, we are using our own mechanism for the user history.

**Comment by raghu2094** [comment]
Hi,
So I was able to start the project and run all the microservices. I could verify Auth, Profile and Search service. I can see songs being displayed based on the mood. I can also see user history being stored in profile. How do I check the recommendation service? Where do I need to look for recommended songs?

**Comment by aravindparappil46** [comment]
You have to play at least one song for recommendations to show up.
It will be shown in the home page itself below the search box. (You have to refresh the page)

**Comment by aravindparappil46** [comment]
Regarding the question of why Utopia over Spotify, we had plans of improving the recommendations from Spotify (not in terms of the algorithm but more towards personalized content, say if the user logs in from Bloomington and the local football team has lost a match, we would recommend songs based on that)
We couldn't do those features in the first milestone due to time constraints.

**Comment by raghu2094** [comment]
@aravindparappil46
"play at least one song for recommendations to show up." - Play the song in the sense playing from the music player provided? or clicking on the the song will suffice? The music player isn't working for me

**Comment by aravindparappil46** [comment]
@raghu2094 Just clicking on the card for a track will suffice for recommendations to show up
Clicking on a card will just load the track into the player. To actually play the song, you need to hit the play button. 
This has been raised during the peer review #51 . However, was closed by the reviewer. We can reopen it or create a new issue (as #51 had two issues in it) as per your suggestion

**Comment by raghu2094** [comment]
Ok. I have completed reviewing the project. All the micro-services are working fine. UI looks impressive. 
In the UI, you should include a way to distinguish between the songs based on the mood and recommended songs based on user history. Something like a " Here are your recommended songs based on your recent songs" or "These are the songs based on your mood" message. If you could make the music player working, that would be awesome. But you can keep it as an enhancement and prioritize important tasks first for the upcoming milestone.

Documentation was fine but not up to the mark. Steps for starting the project were clear. Arch and napkin diagram describe the services of the application perfectly.
Few pointers for your documentation:
1) Include user stories
3) If there are pre-requisites, always include a link to download/with installation steps.
2) Description of working of each service is expected to be longer than a sentence. Reader should at the least have a basic understanding of how your application is working which was missing. Please keep this in mind for future assignments.
Also, Considering you are a 4 member team, the quality of the work is expected to be slightly better compared to other teams.
Please work on it in the upcoming assignments.    

Good job and All the best!

**Comment by raghu2094** [comment]
Reopening to add one suggestion.
Currently it seems as if majority of the things is being already provided by the API. Please think of how you can come with new features using the data being provided by the API. As already mentioned, we will be expecting more work from the team as we progess through the rest of the assignments.
