### ISSUE TITLE
Create Jenkins script to install dependencies

### ISSUE THREAD

**Issue by aravindparappil46** [airavata-courses/Team-Rocket#97]
All Node, python, go, ruby dependencies should get installed on the VMs through a shell script

**Comment by sairohithA007** [comment]
**Below are the commands:**

AuthServices:
sudo yum update
sudo yum install -y firewalld
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --zone=public --add-port=5001/tcp --permanent
sudo firewall-cmd --reload
sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm 
sudo yum install -y python36u python36u-libs python36u-devel python36u-pip 
cd Team-Rocket/AuthServices 
sudo pip3.6 install -r requirements.txt
nohup python3.6 -m Controllers.user_controller &

ProfileServices:
sudo yum install -y nodejs
nohup node server.js &
sudo yum install -y firewalld
sudo firewall-cmd --zone=public --add-port=3001/tcp --permanent
sudo firewall-cmd --reload

APIBroker:
sudo yum install -y nodejs
nohup node server.js &
sudo yum install -y firewalld
sudo firewall-cmd --zone=public --add-port=3002/tcp --permanent
sudo firewall-cmd --reload

UI:
sudo yum install -y nodejs
nohup nom run client &
sudo yum install -y firewalld
sudo firewall-cmd --zone=public --add-port=3000/tcp --permanent
sudo firewall-cmd --reload

RecommendationEngine:
wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
sha256sum go1.10.3.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.10.3.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
source ~/.bash_profile
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/centos/Team-Rocket/RecoEngineWorkspace
cd Team-Rocket/RecoEngineWorkspace
go get ./…
cd src/RecommendationEngine/
go build
./RecommendationEngine
sudo yum install -y firewalld
sudo firewall-cmd --zone=public --add-port=8001/tcp --permanent
sudo firewall-cmd --reload

APIGateway:
sudo yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel
curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc
rbenv install 2.6.0
rbenv global 2.6.0
cd Team-Rocket/APIGateway 
gem update --system
gem install -y bundler
bundler update --bundler
gem install -y bundler
gem install rails
gem install zookeeper
bundle install 
nohup ails server --binding 0.0.0.0 --port 3003 &
sudo yum install -y firewalld
sudo firewall-cmd --zone=public --add-port=3003/tcp --permanent
sudo firewall-cmd --reload

**Comment by aravindparappil46** [comment]
Hi Sai,
Isn't the port for Auth Services 5001? Because I noticed that you were mentioning the right PORT_NUMBER but the firewalld was unblocking 5001.

**Comment by sairohithA007** [comment]
Thanks @aravindparappil46, I made the necessary change in the same comment above.

**Comment by aravindparappil46** [comment]
@sairohithA007 we should do npm install for APIBroker and ProfileServices too, right? to install all packages?

**Comment by sairohithA007** [comment]
Yes we are supposed to run "npm install". Double check the commands while running commands through Jenkins and add the commands.

**Comment by aravindparappil46** [comment]
@sairohithA007  Ok. couldn't find it in the script here. Will add myself. Also, branch 98 (where package.json has been modified) should be merged with Project-2

**Comment by aravindparappil46** [comment]
Updated all Jenkins scripts at respective Jobs over at Jenkins master.
Jenkins runs at http://149.165.170.7:8080
See under Utopia Jobs view for each job's details. Description also provided for each job

**Comment by aravindparappil46** [comment]
This is done with Kubernetes now.
